name: todoapp

services: 
  frontend: 
    build: ./frontend
    image: todoapp-frontend
    ports: 
      - "3001:3000"

  backend: 
    build: ./backend
    image: todoapp-backend
    ports:
       - "5000:5000"
